workspace:
  base: /go
  path: src/github.com/zanetworker/dockument

pipeline:
  build: 
    image: golang
    commands: 
      - make OS=linux dry 
  lint:
    image: golang
    commands:
      - make lint 
  test: 
    image: golang
    commands: 
      - make test