FROM golang:alpine as builder
MAINTAINER Jessica Frazelle <jess@linux.com>

LABEL com.example.api="ACME Incorporated"
LABEL com.example.variables="ACME Incorporated"

ENV PATH /go/bin:/usr/local/go/bin:$PATH
ENV GOPATH /go

